Repository stolostron/kui-web-terminal, pull requests merged in 2021-07, with the labels that each got.

#260 style fixes for search plugin
  client/package-lock.json
  client/styles/mcm-kui.scss
  client/styles/search-overrides.scss
  proxy/package-lock.json
Labels: approved

#261 more css fixes for the search plugin UI
  client/package-lock.json
  client/styles/search-overrides.scss
Labels: approved, lgtm

#262 fix overflow style for search results table
  client/styles/search-overrides.scss
Labels: approved, lgtm

#263 update search plugin with focus fix
  client/package-lock.json
  download-plugins.sh
  plugin-downloads/plugin-search.tgz
  proxy/package-lock.json
Labels: approved, lgtm

#259 updated search plugin version to v2.2.2
  client/package-lock.json
  download-plugins.sh
  plugin-downloads/plugin-search.tgz
Labels: lgtm

#266 add comment to Makefile to trigger no-op build
  Makefile
Labels: approved, lgtm

#267 changes for new base image
  Dockerfile
Labels: approved, lgtm
