Repository stolostron/kui-web-terminal, pull requests merged in 2021-04, with the labels that each got.

#230 update search plugin
  client/package-lock.json
  download-plugins.sh
  plugin-downloads/plugin-search.tgz
Labels: lgtm

#231 update 2.3 image to use NodeJS v14
  .travis.yml
  Dockerfile
  client/package-lock.json
  proxy/package-lock.json
Labels: approved, lgtm

#232 move kui-shell/builder to devDeps in proxy
  proxy/package-lock.json
  proxy/package.json
Labels: approved, lgtm

#233 Prow onboarding work
  COMPONENT_VERSION
  Dockerfile.prow
  Makefile.prow
  RELEASE_VERSION
Labels: approved

#235 increase wait between publish of image and test image for 2.2
  .travis.yml
Labels: lgtm
